name: Develop hosting deploy

on:
  push:
    branches: [smcclure17/web-ui]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    defaults:
      run:
        working-directory: public
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - name: Install dependencies
        run: yarn install && yarn build
      - name: Deploy hosting
        run: npx firebase deploy --only hosting --project develop

