name: Firebase functions deploy

env:
  # Name of firebase project to deploy to. If on develop, use dev project, if on main use prod.
  # Production and develop projects are configured in `.firebaserc`
  FIREBASE_PROJECT: ${{ ( github.ref_name == 'main') && 'production' || 'develop' }}

on:
  push:
    branches: [main, develop]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: 
      name: '${{ env.FIREBASE_PROJECT }}'
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.FIREBASE_CI_SERVICE_ACCOUNT }}'
      - name: Install dependencies
        run: yarn global add firebase-tools && yarn install
      - name: Deploy functions
        run: |
          echo "Deploying to ${{ env.FIREBASE_PROJECT }}..."
          firebase deploy --only functions --project ${{ env.FIREBASE_PROJECT }}
          echo "Finished deploy to ${{ env.FIREBASE_PROJECT }}."
