name: Production Firebase functions deploy

on:
  push:
    branches: [main]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - name: Install dependencies
        run: yarn global add firebase-tools && yarn install
      - name: Deploy functions
        run: |
          firebase deploy --only functions --project production