name: Production hosting deploy

on:
  push:
    branches: [production]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: 
      name: production
    defaults:
      run:
        working-directory: public
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - name: Install dependencies
        run: yarn install && yarn global add firebase-tools && yarn build
      - name: Deploy hosting
        run: firebase deploy --only hosting --project production

