name: Run unit tests
on:
  push:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    environment: develop
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - name: Install dependencies and create build
        run: yarn install && yarn build
      - name: Select Firebase project and run tests
        run: yarn firebase use develop && yarn test
